### ISSUE TITLE
lava 出错：Proxy connection ended before receiving CONNECT response

### ISSUE THREAD

**Issue by Hujunjob** [0xsongsu/dailytask#10]
查询地址 0xcF9FFdb1494B0F4B11B9A73f536148aAB84DFdBA 出错: request to https://eth1.lava.build/lava-referer-53a88785-d033-48e2-9dac-e7d30f3c7aab/ failed, reason: Proxy connection ended before receiving CONNECT response

**Comment by Hujunjob** [comment]
我在https://app.proxy-cheap.com/购买的proxy

**Comment by 0xsongsu** [comment]
代理问题，检查有没有填对，或者重试运行

**Comment by Hujunjob** [comment]
可以了，把proxy host name改为proxy ip就行了
