### ISSUE TITLE
lava报错，求助

### ISSUE THREAD

**Issue by kingchan9527** [0xsongsu/dailytask#11]
Using RPC: undefined
查询地址 0xfE140Ee27159CA2b19b7Eff3CE72195c4eb839E6 出错: Invalid URL
Using RPC: undefined
查询地址 0xE5Ce4c47b4a87351CEBaf4d9D48d7851Be132B20 出错: Invalid URL
Using RPC: undefined
查询地址 0xc4700FBc12fC000180D808863F7543dCA1Ae0fDC 出错: Invalid URL
Using RPC: undefined
查询地址 0x205053e29F84372130F7FfEc9f0Af5EAbdB21e02 出错: Invalid URL
Using RPC: undefined

**Comment by kingchan9527** [comment]
![1709977609641](https://github.com/0xsongsu/dailytask/assets/41640366/788c93ba-c88d-4bf3-9270-730144df52d1)
![微信图片_20240309174406](https://github.com/0xsongsu/dailytask/assets/41640366/bc9d7393-ff67-417f-a68d-71e875685da7)
代理我填的这部分

**Comment by kingchan9527** [comment]
Using RPC: undefined
查询地址 0x9a7e039fe50456b88BA4cB92C00fA6d8b827de1e 出错: Only absolute URLs are supported
Using RPC: undefined
查询地址 0x6018DE916fbD35Ba84dE31688E4b55e1784C3E87 出错: Only absolute URLs are supported
Using RPC: undefined
查询地址 0x5be448fBd26c5d71E5C07C9855650295603B6f1D 出错: Only absolute URLs are supported
Using RPC: undefined
查询地址 0x6bB95f9eEE0d2FF48a4d091744013c81A2C9f279 出错: Only absolute URLs are supported

**Comment by kingchan9527** [comment]
> 你需要先运行getLavaRpc.js 看看使用说明

哪里有getLavaRpc.js的运行说明呢，小白求教

**Comment by kingchan9527** [comment]
我在桌面创建了testwallet/wallet，为什么是这个提示呢

**Comment by kingchan9527** [comment]
开始执行脚本: lavaRun
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\Users\KCPC\Desktop\dailytask-main\src\lāvaNet\lavaRun.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0

**Comment by kingchan9527** [comment]
按照readme的步骤一步步来了还是不行唉

**Comment by Le-zhao** [comment]
你ethrpc节点填哪地方了

**Comment by Le-zhao** [comment]
![image](https://github.com/0xsongsu/dailytask/assets/60615241/242ec5f7-ad60-4b5e-8437-3500d75e7c45)

**Comment by kingchan9527** [comment]
> 你ethrpc节点填哪地方了
填在runner.json

**Comment by Le-zhao** [comment]
你问题解决了吗

**Comment by kingchan9527** [comment]
> 你问题解决了吗

解决不了一点
