### ISSUE TITLE
Invalid mnemonic format  格式不对？

### ISSUE THREAD

**Issue by piqihaha** [0xsongsu/dailytask#15]
![image](https://github.com/0xsongsu/dailytask/assets/25221169/5d3f4d2d-b50e-453f-96b5-95deedc3b08b)

**Comment by piqihaha** [comment]
在表格里输入的助记词是正确的，怎么提示格式不对呢

**Comment by 0xsongsu** [comment]
貌似是文档兼容的问题，我更新了一份自动创建钱包的脚本，你可以尝试先自动生成一份，然后把你的助记词放进去就行了

**Comment by piqihaha** [comment]
> 貌似是文档兼容的问题，我更新了一份自动创建钱包的脚本，你可以尝试先自动生成一份，然后把你的助记词放进去就行了

我用GPT 搞好了
const mnemonic = line.trim(); // 去除助记词两端的空格
