### ISSUE TITLE
代理检查不通过

### ISSUE THREAD

**Issue by Hyperpepe** [0xsongsu/dailytask#3]
![image](https://github.com/0xsongsu/dailytask/assets/74920047/e8b90347-5c29-46cd-9e5d-684ee6e7591d)
大哥，代理IP按照你的指示买了，但是貌似是用不了的。
![image](https://github.com/0xsongsu/dailytask/assets/74920047/c29cf08f-a22e-4456-b470-a3006dffde25)
一个是原来的一个是我自己买的，都检查不通过。

**Comment by Hyperpepe** [comment]
貌似是代码的检查手段？
![image](https://github.com/0xsongsu/dailytask/assets/74920047/d3951ca3-8eb3-49ba-84cf-3b0b54f242a3)
我使用代理商给的curl示例进行的卷曲

**Comment by 0xsongsu** [comment]
我这边是没问题的，你检查一下你的梯子，关掉&打开再试一下

**Comment by Hyperpepe** [comment]
切换梯子需要切换到对应的国家去还是关掉呢，全局？

**Comment by 0xsongsu** [comment]
不需要对应的国家，试试全局吧
