### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by ananzeng** [0xsongsu/dailytask#4]
地址读取完毕
开始领取测试币
[
  '0xc730b70d0cd19c916df64b36a5896078652f3429'
]
测试代理IP是否正常
验证成功, IP信息:  当前 IP：14.225.60.243  来自于：越南 河内市   vnpt.vn

领取地址: 0xc730b70d0cd19c916df64b36a5896078652f3924
Request failed with status code 400
领取失败❌，地址：0xc730b70d0cd19c916df64b36a5896078652f3924: AxiosError: Request failed with status code 400
...
data: { msg: 'invalid address' }
...
老哥怎麼回事~(地址已脫敏)
地址都是新的

**Comment by 0xsongsu** [comment]
近期会修复这个问题

**Comment by Hyperpepe** [comment]
老哥，还是没办法去检查通过代理。
按照你的教程取得的代理连接，每次检查都是502
![image](https://github.com/0xsongsu/dailytask/assets/74920047/b4ced3b0-b14b-4159-a150-dffd886df7e5)
🤔老哥你是怎么配置的呢？
