### ISSUE TITLE
lava使用报错

### ISSUE THREAD

**Issue by Le-zhao** [0xsongsu/dailytask#8]
按照之前的教程执行新代码，显示报错

**Comment by 0xsongsu** [comment]
贴报错log或者截图，你这说的我算命也算不出来是哪有问题啊

**Comment by Le-zhao** [comment]
> 贴报错log或者截图，你这说的我算命也算不出来是哪有问题啊

![image](https://github.com/0xsongsu/dailytask/assets/60615241/a22b5b28-5a00-4443-bf78-1f7e0c55049c)
更新代码后怎么操作lava，只找到了proxy，那个ethrpc是粘贴到这里吗
![image](https://github.com/0xsongsu/dailytask/assets/60615241/3adb4336-83dd-49e3-ab97-092e93fb806f)

**Comment by Le-zhao** [comment]
> 贴报错log或者截图，你这说的我算命也算不出来是哪有问题啊

你好，我问下walletpath里面三种都是填的什么数据用于刷lava空投
